---
title: "R Notebook"
output: html_notebook
---

```{r}
suppressPackageStartupMessages({
  library(ggplot2)
  library(stringr)
  library(dplyr)
  library(tidyr)
  library(factoextra)
})
```

Load the data
```{r}
data <- read.csv("data/SHS Language_May 1, 2023_14.19.csv", sep=",")
```

Clean up table
```{r}
question_descr <- as.character(data[1,])
data <- data[-c(1,2),]
```

Rename columns
```{r}
colnames(data) <- c("StartDate", "EndDate", "Status", "IPAddress", "Progress", "Duration",
                    "Finished", "RecordedDate", "ResponseId", "RecipientLastName", 
                    "RecipientFirstName", "RecipientEmail", "ExternalReference", 
                    "LocationLatitude", "LocationLongitude", "DistributionChannel", "UserLanguage",
                    "gender", "age", "country", "english",
                    "m_power1", "m_univers1", "m_achieve1", "m_secur1", "m_conform1", "m_benev1",
                    "m_univers2", "m_achieve2", "m_secur2", "m_conform2", "m_power2", "m_benev2", "m_univers3",
                    "f_power1", "f_univers1", "f_achieve1", "f_secur1", "f_conform1", "f_benev1",
                    "f_univers2", "f_achieve2", "f_secur2", "f_conform2", "f_power2", "f_benev2", "f_univers3",
                    "x_power1", "x_univers1", "x_achieve1", "x_secur1", "x_conform1", "x_benev1",
                    "x_univers2", "x_achieve2", "x_secur2", "x_conform2", "x_power2", "x_benev2", "x_univers3",
                    "cont_emis1", "cont_emis2", "cont_emis3",
                    "cont_milk1", "cont_milk2", "cont_milk3",
                    "cont_diver1", "cont_diver2", "cont_diver3",
                    "harm_emis1", "harm_emis2", "harm_emis3",
                    "harm_milk1", "harm_milk2", "harm_milk3",
                    "harm_diver1", "harm_diver2", "harm_diver3",
                    "pure_emis1", "pure_emis2", "pure_emis3",
                    "pure_milk1", "pure_milk2", "pure_milk3",
                    "pure_diver1", "pure_diver2", "pure_diver3")
```

Filter data
```{r}
# minimum duration (in seconds)
min_duration <- 270
# up to which question should the survey be filled
full_upto <- "diver3"
english <- c

data <- data[data$Duration>min_duration, ]
data <- data[rowSums(data[, str_detect(colnames(data), full_upto)] == "") == 2, ]
```

Transform answers to numerical values
```{r}
#encode environmental attitudes
data[data == "Strongly agree"] <- 5
data[data == "Somewhat agree"] <- 4
data[data == "Neither agree nor disagree"] <- 3
data[data == "Somewhat disagree"] <- 2
data[data == "Strongly disagree"] <- 1
data <- mutate_at(data, vars(matches("cont|harm|pure")), as.numeric)

#encode human values scale
data[data == "Very much like me"] <- 6
data[data == "Like me"] <- 5
data[data == "Somewhat like me"] <- 4
data[data == "A little like me"] <- 3
data[data == "Not like me"] <- 2
data[data == "Not like me at all"] <- 1
data[data == "Don't know"] <- NA
data <- mutate_at(data, vars(matches("m_|f_|x_")), as.numeric)
```

Add grouping variables
```{r}
data$framing <- c("cont", "harm", "pure")[apply(data[, c("cont_emis1", "harm_emis1", "pure_emis1")],
                                                1, function(i) which(!is.na(i)))]
```

Summarize variables
```{r}
# sum the environmental attitudes
data$emis1 = rowSums(dplyr::select(data, matches("emis1")), na.rm=TRUE)
data$milk1 = rowSums(dplyr::select(data, matches("milk1")), na.rm=TRUE)
data$diver1 = rowSums(dplyr::select(data, matches("diver1")), na.rm=TRUE)
data$emis2 = rowSums(dplyr::select(data, matches("emis2")), na.rm=TRUE)
data$milk2 = rowSums(dplyr::select(data, matches("milk2")), na.rm=TRUE)
data$diver2 = rowSums(dplyr::select(data, matches("diver2")), na.rm=TRUE)
data$emis3 = rowSums(dplyr::select(data, matches("emis3")), na.rm=TRUE)
data$milk3 = rowSums(dplyr::select(data, matches("milk3")), na.rm=TRUE)
data$diver3 = rowSums(dplyr::select(data, matches("diver3")), na.rm=TRUE)
data$emis = rowSums(dplyr::select(data, matches("emis")), na.rm=TRUE)
data$milk = rowSums(dplyr::select(data, matches("milk")), na.rm=TRUE)
data$diver = rowSums(dplyr::select(data, matches("diver")), na.rm=TRUE)
data$envir = rowSums(data[,c("emis", "milk", "diver")], na.rm=TRUE)

# center the values based on the response scale
data$mrat = rowMeans(dplyr::select(data, matches("m_|f_|x_")), na.rm=TRUE)
data$power = rowMeans(dplyr::select(data, matches("power"))-data$mrat, na.rm=TRUE)
data$univers = rowMeans(dplyr::select(data, matches("univers"))-data$mrat, na.rm=TRUE)
data$achieve = rowMeans(dplyr::select(data, matches("achieve"))-data$mrat, na.rm=TRUE)
data$secur = rowMeans(dplyr::select(data, matches("secur"))-data$mrat, na.rm=TRUE)
data$conform = rowMeans(dplyr::select(data, matches("conform"))-data$mrat, na.rm=TRUE)
data$benev = rowMeans(dplyr::select(data, matches("benev"))-data$mrat, na.rm=TRUE)

data$power1 = rowMeans(dplyr::select(data, matches("power1"))-data$mrat, na.rm=TRUE)
data$univers1 = rowMeans(dplyr::select(data, matches("univers1"))-data$mrat, na.rm=TRUE)
data$achieve1 = rowMeans(dplyr::select(data, matches("achieve1"))-data$mrat, na.rm=TRUE)
data$secur1 = rowMeans(dplyr::select(data, matches("secur1"))-data$mrat, na.rm=TRUE)
data$conform1 = rowMeans(dplyr::select(data, matches("conform1"))-data$mrat, na.rm=TRUE)
data$benev1 = rowMeans(dplyr::select(data, matches("benev1"))-data$mrat, na.rm=TRUE)
data$power2 = rowMeans(dplyr::select(data, matches("power2"))-data$mrat, na.rm=TRUE)
data$univers2 = rowMeans(dplyr::select(data, matches("univers2"))-data$mrat, na.rm=TRUE)
data$achieve2 = rowMeans(dplyr::select(data, matches("achieve2"))-data$mrat, na.rm=TRUE)
data$secur2 = rowMeans(dplyr::select(data, matches("secur2"))-data$mrat, na.rm=TRUE)
data$conform2 = rowMeans(dplyr::select(data, matches("conform2"))-data$mrat, na.rm=TRUE)
data$benev2 = rowMeans(dplyr::select(data, matches("benev2"))-data$mrat, na.rm=TRUE)
data$univers3 = rowMeans(dplyr::select(data, matches("univers3"))-data$mrat, na.rm=TRUE)

is.nan.data.frame <- function(x) {
  do.call(cbind, lapply(x, is.nan))
}
data[is.nan(data)] <- NA
```

```{r}
hist(data$power, breaks=30)
hist(data$univers, breaks=30)
hist(data$achieve, breaks=30)
hist(data$secur, breaks=30)
hist(data$conform, breaks=30)
hist(data$benev, breaks=30)
```

```{r}
library(corrplot)
values_cor <- cor(data[, c("power", "univers", "achieve", "secur", "conform", "benev")])
corrplot(values_cor, method="color")
```


PCA based on values
```{r}
pca_values <- prcomp(na.omit(data[, c("power1", "univers1", "achieve1", "secur1", "conform1", "benev1",
                              "power2", "univers2", "achieve2", "secur2", "conform2", "benev2", "univers3")]), scale=TRUE)
fviz_pca_ind(pca_values, label="none")
```

PCA based on attitudes
```{r}
pca_envir <- prcomp(na.omit(data[, c("milk1", "emis1", "diver1", "milk2", "emis2", "diver2", "milk3", "emis3", "diver3")]), scale=TRUE)
fviz_pca_ind(pca_envir, label="none", col.ind = log(as.numeric(data$Duration)))
```



```{r}
ggplot(data, aes(x=gender, y=envir))+
  geom_boxplot()
```


```{r}
ggplot(data, aes(x=framing, y=emis))+
  geom_boxplot()
```

```{r}
ggplot(data, aes(x=framing, y=milk))+
  geom_boxplot()
```

```{r}
ggplot(data, aes(x=framing, y=diver))+
  geom_boxplot()
```

```{r}
ggplot(data, aes(x=univers, y=envir))+
  geom_point()+
  geom_smooth(method='lm', formula='y~x')
ggplot(data, aes(x=univers, y=milk))+
  geom_point()+
  geom_smooth(method='lm', formula='y~x')
ggplot(data, aes(x=univers, y=diver))+
  geom_point()+
  geom_smooth(method='lm', formula='y~x')
ggplot(data, aes(x=univers, y=emis))+
  geom_point()+
  geom_smooth(method='lm', formula='y~x')
ggplot(data, aes(x=univers, y=milk3))+
  geom_point()+
  geom_smooth(method='lm', formula='y~x')
ggplot(data, aes(x=univers, y=diver3))+
  geom_point()+
  geom_smooth(method='lm', formula='y~x')
ggplot(data, aes(x=univers, y=emis3))+
  geom_point()+
  geom_smooth(method='lm', formula='y~x')
```


```{r}
ggplot(data, aes(x=power, y=envir, color=framing))+
  geom_point()+
  geom_smooth(method='lm', formula='y~x')
ggplot(data, aes(x=univers, y=envir, color=framing))+
  geom_point()+
  geom_smooth(method='lm', formula='y~x')
ggplot(data, aes(x=achieve, y=envir, color=framing))+
  geom_point()+
  geom_smooth(method='lm', formula='y~x')
ggplot(data, aes(x=secur, y=envir, color=framing))+
  geom_point()+
  geom_smooth(method='lm', formula='y~x')
ggplot(data, aes(x=conform, y=envir, color=framing))+
  geom_point()+
  geom_smooth(method='lm', formula='y~x')
ggplot(data, aes(x=benev, y=envir, color=framing))+
  geom_point()+
  geom_smooth(method='lm', formula='y~x')
```


```{r}
data %>%
  mutate(high_secur = secur>median(secur)) %>%
  ggplot(aes(x=framing, y=envir, color=high_secur))+
  geom_boxplot()
data %>%
  mutate(high_univers = univers>median(univers)) %>%
  ggplot(aes(x=framing, y=envir, color=high_univers))+
  geom_boxplot()
data %>%
  mutate(high_achieve = achieve>median(achieve)) %>%
  ggplot(aes(x=framing, y=envir, color=high_achieve))+
  geom_boxplot()
data %>%
  mutate(high_power = power>median(power)) %>%
  ggplot(aes(x=framing, y=envir, color=high_power))+
  geom_boxplot()
data %>%
  mutate(high_conform = conform>median(conform)) %>%
  ggplot(aes(x=framing, y=envir, color=high_conform))+
  geom_boxplot()
data %>%
  mutate(high_benev = benev>median(benev)) %>%
  ggplot(aes(x=framing, y=envir, color=high_benev))+
  geom_boxplot()
```


```{r}
model_power <- lm(envir ~ power*framing, data=data)
model_univers <- lm(envir ~ univers*framing, data=data)
model_achieve <- lm(envir ~ achieve*framing, data=data)
model_secur <- lm(envir ~ secur*framing, data=data)
model_conform <-lm(envir ~ conform*framing, data=data)
model_benev <- lm(envir ~ benev*framing, data=data)
```

```{r}
model_power <- lm(diver ~ power*framing, data=data)
model_univers <- lm(diver ~ univers*framing, data=data)
model_achieve <- lm(diver ~ achieve*framing, data=data)
model_secur <- lm(diver ~ secur*framing, data=data)
model_conform <-lm(diver ~ conform*framing, data=data)
model_benev <- lm(diver ~ benev*framing, data=data)
```

```{r}
model_power <- lm(milk ~ power*framing, data=data)
model_univers <- lm(milk ~ univers*framing, data=data)
model_achieve <- lm(milk ~ achieve*framing, data=data)
model_secur <- lm(milk ~ secur*framing, data=data)
model_conform <-lm(milk ~ conform*framing, data=data)
model_benev <- lm(milk ~ benev*framing, data=data)
```

```{r}
summary(model_power)
summary(model_univers)
summary(model_achieve)
summary(model_secur)
summary(model_conform)
summary(model_benev)
```





